// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB30YYSMMxhCioh5FzP_vKpwInOeLNHUPw',
    appId: '1:214802389261:web:e4189f38661f5e25583844',
    messagingSenderId: '214802389261',
    projectId: 'memory-lane-16aa9',
    authDomain: 'memory-lane-16aa9.firebaseapp.com',
    storageBucket: 'memory-lane-16aa9.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBULJ8DN6G0bLkrnimGgm6ZSkOofv-3bL8',
    appId: '1:214802389261:android:ea1989d366d9ca8d583844',
    messagingSenderId: '214802389261',
    projectId: 'memory-lane-16aa9',
    storageBucket: 'memory-lane-16aa9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG2aT9YeY2VBD8jc1bWsGzwUh-zEEUHWg',
    appId: '1:214802389261:ios:b11e6f7819f21a3b583844',
    messagingSenderId: '214802389261',
    projectId: 'memory-lane-16aa9',
    storageBucket: 'memory-lane-16aa9.firebasestorage.app',
    iosBundleId: 'com.example.firbaseConnecting',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG2aT9YeY2VBD8jc1bWsGzwUh-zEEUHWg',
    appId: '1:214802389261:ios:b11e6f7819f21a3b583844',
    messagingSenderId: '214802389261',
    projectId: 'memory-lane-16aa9',
    storageBucket: 'memory-lane-16aa9.firebasestorage.app',
    iosBundleId: 'com.example.firbaseConnecting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB30YYSMMxhCioh5FzP_vKpwInOeLNHUPw',
    appId: '1:214802389261:web:80f9920d5b32f80d583844',
    messagingSenderId: '214802389261',
    projectId: 'memory-lane-16aa9',
    authDomain: 'memory-lane-16aa9.firebaseapp.com',
    storageBucket: 'memory-lane-16aa9.firebasestorage.app',
  );
}
